import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />

        {/* Main Min Height = Screen - NavBar */}
        <main className="grainy-light flex min-h-[calc(100vh-3.5rem-1px)] flex-col">
          {/* To push the footer to bottom: Content Height = 100% & Flex = 1  */}
          <div className="flex h-full flex-1 flex-col">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
